# Don't print a new line at the start of the prompt
add_newline = false

[directory]
truncation_length = 7
truncation_symbol = "…/"

[aws]
disabled = true
[gcloud]
disabled = true

[helm]
disabled = true

[dotnet]
disabled = true
[java]
disabled = true
[perl]
disabled = true
[php]
disabled = true

[hostname]
ssh_only = true
disabled = true
