#!/usr/bin/env sh

# Called by sxiv(1) whenever an image gets loaded.
# The output is displayed in sxiv's status bar.
# Arguments:
#   $1: path to image file
#   $2: image width
#   $3: image height

s=" | " # field separator

filename=$(basename "$1")
filesize=$(du -Hh "$1" | cut -f 1)

# Requires ImageMagick
# The '[0]' stands for the first frame of a multi-frame file, e.g. gif
geometry=$(identify -format '%G' "$1[0]")

echo "${filesize}${s}${geometry}${s}${filename}"
