#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

setxkbmap -model pc101 -layout us -variant altgr-intl -option -option lv3=ralt_switch -option compose=rctrl -option terminate=ctrl_alt_bksp

xset dpms 180 180 300  &&  xset r rate 400 40

xwallpaper --zoom $HOME/Pictures/wall.jpg

exec i3

