#!/usr/bin/env sh

export XSECURELOCK_SHOW_DATETIME=1
export XSECURELOCK_DATETIME_FORMAT='%a %d %b %H:%M:%S'
export XSECURELOCK_AUTH_BACKGROUND_COLOR=#262626
export XSECURELOCK_AUTH_FOREGROUND_COLOR=#D0BFA1
export XSECURELOCK_AUTH_WARNING_COLOR=#FF5F00
export XSECURELOCK_FONT='Hack Nerd Font'
export XSECURELOCK_COMPOSITE_OBSCURER=0

xsecurelock
