
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=25000
export SAVEHIST=25000

# Change the $PATH
export PATH="/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:$PATH"

# User configuration

# Set language environment
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Preferred editor
export EDITOR='nvim'
export VISUAL=$EDITOR

export TERM=$(which alacritty)
export BROWSER=$(which firefox)

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# SSH
export SSH_KEY_PATH="$HOME/.ssh/id_ecdsa"
# GPG
export GPG_TTY=$(tty)

# Aliases
source $HOME/.config/aliases/aliases

# Scripts
source $HOME/.config/zsh/scripts.zsh
